/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Odev_uc;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Moaaz Gabllah
 */
public class Program extends javax.swing.JFrame {

    /**
     * Creates new form Program
     */
    static FileIslelemri fileIslemi= new FileIslelemri();;
    DefaultListModel dm1=new DefaultListModel();
    DefaultListModel<String> dm11=new DefaultListModel<String>();
    DefaultListModel<String> dm12=new DefaultListModel<String>();
    public Program() throws IOException {
        initComponents();
        this.setVisible(true);
        fileIslemi.fileislemi();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.LIGHT_GRAY);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextKullaniciId = new javax.swing.JTextField();
        jButtonFilmleriSirala = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListOnerilenFilmler = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListIzlenenFilmler = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListIzlenenOrtakFilmSayisi = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextKullaniciId.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonFilmleriSirala.setText("FİLİMLERİ SIRALA");
        jButtonFilmleriSirala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilmleriSiralaActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Izlenen Ortak Film Sayısı :");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Önerilen Filmler :");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Izlenen Filmler :");

        jScrollPane1.setViewportView(jListOnerilenFilmler);

        jScrollPane2.setViewportView(jListIzlenenFilmler);

        jScrollPane3.setViewportView(jListIzlenenOrtakFilmSayisi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(398, 398, 398)
                .addComponent(jTextKullaniciId, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jButtonFilmleriSirala, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextKullaniciId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFilmleriSirala, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // this method take two users and return common movies
    int ortakFilimlerinSayisiBul(Kullanici user1, Kullanici user2) {
        int ortakFilimlerSayisi=0;
        Node<Film> temp1 = user1.izledigi_filmler.getHeader();
        Node<Film> temp2 = user2.izledigi_filmler.getHeader();
        while (temp1 != null) {       
            temp2 = user2.izledigi_filmler.getHeader();
            while (temp2 != null) {
                if (temp1.data.getFilm_id()<temp2.data.getFilm_id()) {
                    break;
                }
                if (temp1.data.getFilm_id() == temp2.data.getFilm_id()) {
                    ortakFilimlerSayisi++;
                    temp2 = temp2.nextNode;
                    break;
                }
                temp2 = temp2.nextNode;
            }
            temp1=temp1.nextNode;
        }
        return ortakFilimlerSayisi;
    }

    // to find kullanici by id 
    Kullanici findUserById(int id) {
        Node<Kullanici> temp = FileIslelemri.kullanicilar.getHeader();
        while (temp != null) {            
            if (temp.data.getKullanici_id() == id) {
                return temp.data;
            }
            temp=temp.nextNode;
        }
        // because of return statment
        return null;
        //throw new MyException("Kullanici bulunamadi findUserById'de!!");
    }
    
    private void jButtonFilmleriSiralaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilmleriSiralaActionPerformed
        dm1.clear();
        dm11.clear();
        dm12.clear();
        Pattern p=Pattern.compile("[^0-9]");
        Matcher m=p.matcher(jTextKullaniciId.getText().substring(1));
        if(m.find()){
            JOptionPane.showMessageDialog(null, "Lütfen doğru kullanıcı giriniz ( c50 ) !!");
            jTextKullaniciId.setText("");
            return;
        }
        int Userid = Integer.parseInt(jTextKullaniciId.getText().substring(1));
        // add the movies that user had seen to the first List
        Kullanici user=findUserById(Userid);
        if(user==null){
            JOptionPane.showMessageDialog(null, "Lütfen c0 - c99 arası bir kullanıcı giriniz !!");
            jTextKullaniciId.setText("");
            return;
        }
        Node<Film> tempFilm=user.getIzledigi_filmler().getHeader();
        while (tempFilm!=null) {       
            dm1.addElement(String.valueOf(tempFilm.data.film_name));
            tempFilm=tempFilm.nextNode;
        }
        jListIzlenenFilmler.setModel(dm1);
        // izlenen film listesi eklnedi
        
        Node<Kullanici>tempUser=FileIslelemri.kullanicilar.getHeader();
        
        LinkedListQueue<Kullanici> siraliListe=new LinkedListQueue();        
        while(tempUser!=null){
            if (user==tempUser.data) {
                tempUser=tempUser.nextNode;
                continue;
            }
            tempUser.data.secilenKullanicilaOrtakFilmSayisi=ortakFilimlerinSayisiBul(user,tempUser.data);
            siraliListe.siraliEkle(tempUser.data);            
            tempUser=tempUser.nextNode;
        }
        Node<Kullanici> tmpNode=siraliListe.getHeader();
        while (tmpNode!=null) {            
            dm11.addElement("c"+user.getKullanici_id()+"-c"+tmpNode.data.getKullanici_id()+" similarity = "+((Kullanici)tmpNode.data).secilenKullanicilaOrtakFilmSayisi);
            tmpNode=tmpNode.nextNode;
        }
        jListIzlenenOrtakFilmSayisi.setModel(dm11);
        // izlenen ortak film sayisi eklnedi

       // listede birinci user Film icin
        Node<Film> tmpFilmNode=siraliListe.getHeader().data.izledigi_filmler.getHeader();
        // disiridan alinan user
        tempFilm=user.getIzledigi_filmler().getHeader();        
        int flag=0;
        while(tmpFilmNode!=null){
            tempFilm=user.izledigi_filmler.getHeader();
            flag=0;
            while(tempFilm!=null){
                if (tmpFilmNode.data.film_name.equalsIgnoreCase(tempFilm.data.film_name)) {
                    flag=1;
                    break;
                } 
                tempFilm=tempFilm.nextNode;
            }
            if (flag==0) {
                dm12.addElement(tmpFilmNode.data.film_name);
            }
            tmpFilmNode=tmpFilmNode.nextNode;
        }
        jListOnerilenFilmler.setModel(dm12);
        // Orenilen filmler basariyla yazildi
    }//GEN-LAST:event_jButtonFilmleriSiralaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Program().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
                    throw new MyException("Hata program class main de !!");
                }
            }
        });
        /*
        try {
            fileIslemi.fileislemi();
        } catch (IOException ex) {
            Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
            throw new MyException("Hata program class main de !!");
        }*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFilmleriSirala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jListIzlenenFilmler;
    private javax.swing.JList jListIzlenenOrtakFilmSayisi;
    private javax.swing.JList jListOnerilenFilmler;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextKullaniciId;
    // End of variables declaration//GEN-END:variables
}
